name: GitHub Pages Configuration

on:
  workflow_dispatch:
  push:
    branches:
      - gh-pages

jobs:
  configure-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Verify index.html exists at the root
      - name: Verify index.html
        run: |
          if [ ! -f "index.html" ]; then
            echo "Creating index.html redirect file"
            cat << 'EOF' > index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Redirecting to Lemonade Map</title>
  <script>window.location.href = "./lemonade-map/";</script>
</head>
<body>
  <p>
    If you are not redirected automatically, follow this
    <a href="./lemonade-map/">link to the Lemonade Map application</a>.
  </p>
</body>
</html>
EOF
          fi