name: GitHub Pages Configuration

on:
  workflow_dispatch:
  push:
    branches:
      - gh-pages

jobs:
  configure-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          # Enable custom domain if CNAME exists
          enablement: true
          # Set the source branch to gh-pages
          source_branch: gh-pages
          # Set the source directory to the root
          source_dir: /
          # Enable HTTPS enforcement
          enforce_https: true
          # Enable custom 404 page
          static_site_generator: true
          
      # Verify index.html exists at the root
      - name: Verify index.html
        run: |
          if [ ! -f "index.html" ]; then
            echo "Creating index.html redirect file"
            cat > index.html << 'EOL'
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Redirecting to Lemonade Stand</title>
  <script>
    window.location.href = "./index.html";
  </script>
</head>
<body>
  <p>If you are not redirected automatically, follow this <a href="./index.html">link to the Lemonade Stand application</a>.</p>
</body>
</html>
EOL
          fi