name: Deploy to GitHub Pages (Alternative)

on:
  workflow_dispatch:
  # Disable automatic triggers to avoid conflicts with deploy.yml
  # push:
  #   branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "lemonade-map/package-lock.json"

      - name: Install dependencies
        run: |
          cd lemonade-map
          npm ci

      - name: Build (includes sitemap generation)
        run: |
          cd lemonade-map
          npm run build

      # Copy the root index.html redirect file to the dist directory
      - name: Ensure correct index.html
        run: |
          # Make sure the dist directory exists
          mkdir -p lemonade-map/dist
          # Copy 404.html to the root of the dist directory
          cp lemonade-map/public/404.html lemonade-map/dist/
          # Create CNAME file in the dist directory
          echo "lemonademap.com" > lemonade-map/dist/CNAME
          # Create .nojekyll file to disable Jekyll processing
          touch lemonade-map/dist/.nojekyll
          # No need for a redirect in index.html since we're using a custom domain with root path
          # The main application index.html will be used directly

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "lemonade-map/dist"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
